# Generated by Django 3.2.7 on 2022-04-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='ngo_id',
        ),
        migrations.AddField(
            model_name='blogs',
            name='ngo_id',
            field=models.ManyToManyField(to='account.Ngo'),
        ),
    ]
