# Generated by Django 3.2.7 on 2022-04-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220418_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='needy',
            old_name='adress',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='needy',
            name='zip',
        ),
        migrations.AddField(
            model_name='needy',
            name='city',
            field=models.CharField(default='City', max_length=50),
        ),
        migrations.AddField(
            model_name='needy',
            name='people_id',
            field=models.ManyToManyField(to='account.People'),
        ),
        migrations.AddField(
            model_name='needy',
            name='pin',
            field=models.CharField(default='Pin', max_length=30),
        ),
        migrations.AddField(
            model_name='needy',
            name='state',
            field=models.CharField(default='State', max_length=50),
        ),
    ]
