# Generated by Django 3.2.7 on 2022-04-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220418_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='photo',
            field=models.ImageField(blank='True', null='True', upload_to='images/'),
            preserve_default='True',
        ),
    ]
