# Generated by Django 3.2.7 on 2022-04-19 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220420_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solved_cases',
            old_name='needy_id',
            new_name='needy_name',
        ),
        migrations.RenameField(
            model_name='solved_cases',
            old_name='ngo_id',
            new_name='ngo_name',
        ),
        migrations.RenameField(
            model_name='solved_cases',
            old_name='user_id',
            new_name='user_name',
        ),
    ]
