# Generated by Django 3.2.7 on 2022-04-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220420_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='user_id',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='user_name',
            field=models.CharField(default='Person Name', max_length=100),
        ),
        migrations.RemoveField(
            model_name='solved_cases',
            name='needy_name',
        ),
        migrations.AddField(
            model_name='solved_cases',
            name='needy_name',
            field=models.CharField(default='Needy', max_length=100),
        ),
        migrations.RemoveField(
            model_name='solved_cases',
            name='ngo_name',
        ),
        migrations.AddField(
            model_name='solved_cases',
            name='ngo_name',
            field=models.CharField(default='Ngo', max_length=100),
        ),
        migrations.RemoveField(
            model_name='solved_cases',
            name='user_name',
        ),
        migrations.AddField(
            model_name='solved_cases',
            name='user_name',
            field=models.CharField(default='Person', max_length=100),
        ),
    ]
