# Generated by Django 3.2.7 on 2022-04-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220420_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='status',
            field=models.CharField(default='Approach', max_length=11),
        ),
    ]
