# Generated by Django 3.2.7 on 2022-04-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_needy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='user_id',
            field=models.ManyToManyField(to='account.People'),
        ),
        migrations.AddField(
            model_name='solved_cases',
            name='needy_id',
            field=models.ManyToManyField(to='account.Needy'),
        ),
        migrations.AddField(
            model_name='solved_cases',
            name='ngo_id',
            field=models.ManyToManyField(to='account.Ngo'),
        ),
        migrations.AddField(
            model_name='solved_cases',
            name='user_id',
            field=models.ManyToManyField(to='account.People'),
        ),
    ]
